remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise"
title: "Clay Dowling: Ninja"
name: "Clay Dowling"
description: "He was never here."
url: "https://claydowling.github.io/ninja/"
baseusr: "/ninja"
breadcrumbs: true
search_full_content: true
twitter:
        username: ClayDowling
facebook:
        username: ClayDowling

author:
        name: "Clay Dowling"
        bio: "Sneaking ninja."
        location: "Dexter, Michigan, USA"
        email: "clay@lazarusid.com"

kramdown:
        input: GFM
        toc_levels: 1..6
        smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
        - jekyll-paginate
        - jekyll-sitemap
        - jekyll-gist
        - jekyll-feed
        - jemoji

whitelist:
        - jekyll-paginate
        - jekyll-sitemap
        - jekyll-gist
        - jekyll-feed
        - jemoji

category_archive:
        type: liquid
        path: /categories/
tag_archive:
        type: liquid
        path: /tags/


defaults:
        # _posts
        - scope:
                path: ""
                type: posts
          values:
                  layout: single
                  author_profile: true
                  read_time: true
                  comments: false
                  share: true
                  related: true
