remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
title: "Clay Dowling: Ninja"
name: &name "Clay Dowling"
description: "He was never here."

search_full_content: true
twitter:
        username: ClayDowling
facebook:
        username: ClayDowling

author:
        name: *name
        bio: "Sneaking ninja."
        location: "Right where you aren't looking"
        email: "clay@lazarusid.com"

kramdown:
        input: GFM
        toc_levels: 1..6
        smart_quotes: lsquo,rsquo,ldquo,rdquo

category_archive:
        type: liquid
        path: /categories/
tag_archive:
        type: liquid
        path: /tags/


defaults:
        # _posts
        - scope:
                path: ""
                type: posts
          values:
                  layout: single
                  author_profile: true
                  read_time: true
                  comments: false
                  share: true
                  related: true
        # _pages
        - scope:
                path: ""
                type: pages
          values:
                layout: single
                author_profile: true